In [1]:
import sys
sys.path.append('../../src/')

import pandas as pd
import numpy as np
import networkx as nx
import scipy.sparse as sp
from stellargraph import StellarDiGraph

from extract_network import extract_network

2021-12-15 11:44:21.386875: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-15 11:44:25.616385: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 557 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:18:00.0, compute capability: 7.5
2021-12-15 11:44:25.618160: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13524 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:19:00.0, compute capability: 7.5
2021-12-15 11:44:25.619613: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 13524 MB memory:  -> device: 2, name: Tesla T4, pci bus id: 0000:35:00.0, compute capability: 7.5
2021-12-15 11:44:25.621080: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 13524 MB memory:  -> device: 3, name: Tesla T4, pci bus id: 0000:36:00.0, compute capability: 7.5
2021-12-15 11:44:25.622485: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:4 with 13524 MB memory:  -> device: 4, name: Tesla T4, pci bus id: 0000:e7:00.0, compute capability: 7.5
2021-12-15 11:44:25.623928: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:5 with 13524 MB memory:  -> device: 5, name: Tesla T4, pci bus id: 0000:e8:00.0, compute capability: 7.5
2021-12-15 11:44:25.625322: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:6 with 13524 MB memory:  -> device: 6, name: Tesla T4, pci bus id: 0000:f4:00.0, compute capability: 7.5
2021-12-15 11:44:25.626730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:7 with 13524 MB memory:  -> device: 7, name: Tesla T4, pci bus id: 0000:f5:00.0, compute capability: 7.5

In [2]:
data = pd.read_csv('./Business/Business_FM_Full.csv', header=None)
data

,0,1,2,3,4,5,6,7,8,9,...,103,104,105,106,107,108,109,110,111,112
0,0,7,8,2,-2,2,0,7,6,11,...,1,1,-1,0,0,0,0,0,0,-7
1,-7,0,4,7,0,6,2,9,2,7,...,1,0,0,0,0,0,1,1,0,-3
2,-8,-4,0,0,-4,4,-2,-3,2,6,...,6,0,0,0,0,0,0,0,0,-8
3,-2,-7,0,0,-1,0,1,1,-1,3,...,0,0,0,1,0,0,1,1,0,-5
4,2,0,4,1,0,-1,0,4,1,0,...,0,0,0,0,0,0,0,0,0,-3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,0,0,0,0,0,-1,-1,0,0,-4,...,0,0,0,0,0,0,0,0,0,-12
109,0,-1,0,-1,0,0,0,0,-1,0,...,0,0,0,0,0,0,0,0,0,-7
110,0,-1,0,-1,0,0,-3,-5,-1,0,...,0,0,0,0,0,0,0,0,0,-9
111,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-4
112,7,3,8,5,3,7,0,10,7,11,...,5,3,6,5,3,12,7,9,4,0

In [3]:
adj = data.values

In [4]:
adj[adj<0] = 0

In [5]:
adj.min()

0

In [13]:
for subject in ['Business', 'ComputerScience', 'History']:
    adj = pd.read_csv('./'+subject+'/'+subject+'_FM_Full.csv', header=None).values
    adj[adj<0] = 0
    adj = sp.csr_matrix(adj)
    print(adj.shape)
    adj, _ = extract_network(adj, lowest_degree=1)
    print(adj.shape)
    sp.save_npz('./'+subject+'/'+subject+'_FM_Full_adj', adj)

(113, 113)
(113, 113)
(206, 206)
(206, 206)
(145, 145)
(145, 145)